test-py2:
  build: .
  dockerfile: Dockerfile.test-py2
  volumes:
    - ./stolos:/stolos/stolos:ro
    - ./bin:/stolos/bin:ro
    - ./conf:/stolos/conf:ro
    - ./setup.cfg:/stolos/setup.cfg:ro
  links:
    - redis
    - zk
  env_file: conf/stolos-env.sh
  environment:
    - STOLOS_QB_REDIS_HOST="redis:6379"
    - STOLOS_QB_ZOOKEEPER_HOSTS="zk:2181"
    - STOLOS_REDIS_HOST="redis"
test-py3:
  build: .
  dockerfile: Dockerfile.test-py3
  volumes:
    - ./stolos:/stolos/stolos:ro
    - ./bin:/stolos/bin:ro
    - ./conf:/stolos/conf:ro
    - ./setup.cfg:/stolos/setup.cfg:ro
  links:
    - redis3
    - zk3
  env_file: conf/stolos-env.sh
  environment:
    - STOLOS_QB_REDIS_HOST="redis3:6379"
    - STOLOS_QB_ZOOKEEPER_HOSTS="zk3:2181"
    - STOLOS_REDIS_HOST="redis3"

redis3:
  image: "redis:3.0.5"
redis:
  image: "redis:3.0.5"

zk3:
  image: "jplock/zookeeper:3.4.6"
zk:
  image: "jplock/zookeeper:3.4.6"
